/** Canonical action catalog — single source of truth for all action metadata */
export const ACTION_CATALOG = {
  // ── READ ──────────────────────────────────────────────────────────────
  search: {
    category: "read",
    summary: "Search workspace pages/databases",
    args: [{ name: "query", kind: "string", required: true }],
    options: [{ name: "type", kind: "string" }],
    aliases: [],
    output: { kind: "list", defaultFormat: "text", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["find a page", "search workspace"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ['node actions.mjs search "meeting notes"', 'node actions.mjs search "Q1" --type page'],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: true,
      routeLabel: "Find something",
      routeCommand: 'search "query"',
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  getPage: {
    category: "read",
    summary: "Get page content as markdown",
    args: [{ name: "pageId", kind: "id", required: true }],
    options: [{ name: "format", kind: "string" }],
    aliases: ["readPage", "fetchPage", "read", "get"],
    output: { kind: "markdown", defaultFormat: "markdown", supportsRaw: true },
    mutates: false,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["read a page", "get page content"],
    preferInstead: [
      { intent: "copy a page", action: "copyPageWith", reason: "reads + modifies + creates in one call" },
      { intent: "copy with subpages", action: "deepCopy", reason: "full recursive copy" },
    ],
    replacesWorkflows: [],
    examples: ["node actions.mjs getPage abc123", "node actions.mjs getPage abc123 --format raw"],
    skill: {
      includeInQuickPatterns: true,
      includeInDecisionTree: true,
      routeLabel: "Read a page",
      routeCommand: "getPage <id>",
      quickPattern: "Read + summarize/report -> `getPage` -> `createPage` (2 calls)",
      gotchas: ["Returns markdown by default, use --format raw for JSON blocks"],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  getDatabase: {
    category: "read",
    summary: "Get database schema + all entries",
    args: [{ name: "dbId", kind: "id", required: true }],
    options: [],
    aliases: [],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "moderate",
    compound: false,
    preferredFor: ["get database schema", "inspect database"],
    preferInstead: [
      { intent: "query with filters", action: "queryDatabase", reason: "supports filter, sort, and limit" },
    ],
    replacesWorkflows: [],
    examples: ["node actions.mjs getDatabase abc123"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  queryDatabase: {
    category: "read",
    summary: "Query database (markdown table; --format raw for JSON)",
    args: [{ name: "dbId", kind: "id", required: true }],
    options: [
      { name: "filter", kind: "json" },
      { name: "sorts", kind: "json" },
      { name: "limit", kind: "number" },
      { name: "format", kind: "string" },
    ],
    aliases: ["query", "queryDb"],
    output: { kind: "entries", defaultFormat: "markdown", supportsRaw: true },
    mutates: false,
    risk: "low",
    costClass: "moderate",
    compound: false,
    preferredFor: ["list database entries", "filter database", "query database"],
    preferInstead: [
      { intent: "get schema only", action: "getDatabase", reason: "returns schema without querying entries" },
    ],
    replacesWorkflows: [],
    examples: [
      "node actions.mjs queryDatabase abc123",
      `node actions.mjs queryDatabase abc123 --filter '{"property":"Status","select":{"equals":"Done"}}'`,
    ],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: true,
      routeLabel: "Query a database",
      routeCommand: "queryDatabase <dbId>",
      quickPattern: null,
      gotchas: ["Returns markdown table by default, use --format raw for JSON"],
    },
    docs: {
      workflow: true,
      workflowTitle: "Query Database and Create Report",
      workflowNotes: "Returns compact markdown table with row IDs. Use --format raw for full JSON.",
    },
  },

  getTree: {
    category: "read",
    summary: "Hierarchical page/database tree",
    args: [{ name: "pageId", kind: "id", required: true }],
    options: [{ name: "depth", kind: "number" }],
    aliases: [],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "moderate",
    compound: false,
    preferredFor: ["see page hierarchy", "list subpages"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs getTree abc123", "node actions.mjs getTree abc123 --depth 2"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  exportPage: {
    category: "read",
    summary: "Save page as markdown file",
    args: [
      { name: "pageId", kind: "id", required: true },
      { name: "path", kind: "path", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "moderate",
    compound: false,
    preferredFor: ["export page to file", "save page locally"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs exportPage abc123 /tmp/page.md"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  exportDatabase: {
    category: "read",
    summary: "Export as CSV or JSON",
    args: [
      { name: "dbId", kind: "id", required: true },
      { name: "path", kind: "path", required: true },
    ],
    options: [{ name: "format", kind: "string" }],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "moderate",
    compound: false,
    preferredFor: ["export database", "download database"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: [
      "node actions.mjs exportDatabase abc123 /tmp/db.csv",
      "node actions.mjs exportDatabase abc123 /tmp/db.json --format json",
    ],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  getComments: {
    category: "read",
    summary: "All comments on a page",
    args: [{ name: "pageId", kind: "id", required: true }],
    options: [],
    aliases: [],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["read comments", "get page comments"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs getComments abc123"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  getUsers: {
    category: "read",
    summary: "All workspace users",
    args: [],
    options: [],
    aliases: [],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["list users", "get workspace members"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs getUsers"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  // ── WRITE ─────────────────────────────────────────────────────────────
  createPage: {
    category: "write",
    summary: "Create page from markdown",
    args: [
      { name: "parentId", kind: "id", required: true },
      { name: "title", kind: "string", required: true },
      { name: "content", kind: "string", required: false },
    ],
    options: [{ name: "parentType", kind: "string" }],
    aliases: [],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["create a page", "make a new page"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ['node actions.mjs createPage abc123 "My Page" "## Content\\nHello"'],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: true,
      routeLabel: "Create a page",
      routeCommand: 'createPage <parentId> "Title" "markdown content"',
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  updatePage: {
    category: "write",
    summary: "Replace all content (auto-snapshots)",
    args: [
      { name: "pageId", kind: "id", required: true },
      { name: "content", kind: "string", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "medium",
    costClass: "cheap",
    compound: false,
    preferredFor: ["replace page content", "overwrite page"],
    preferInstead: [
      {
        intent: "edit one section",
        action: "replaceSection",
        reason: "surgically replaces one section without touching the rest",
      },
    ],
    replacesWorkflows: [],
    examples: ['node actions.mjs updatePage abc123 "## New content"'],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: true,
      routeLabel: "Replace all content",
      routeCommand: 'updatePage <id> "content"',
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  appendBlocks: {
    category: "write",
    summary: "Append markdown to end of page",
    args: [
      { name: "pageId", kind: "id", required: true },
      { name: "content", kind: "string", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["add content to page", "append to page"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ['node actions.mjs appendBlocks abc123 "## New section\\nContent here"'],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: true,
      routeLabel: "Add to end",
      routeCommand: 'appendBlocks <id> "content"',
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  insertBlocks: {
    category: "write",
    summary: "Insert blocks at position",
    args: [
      { name: "pageId", kind: "id", required: true },
      { name: "content", kind: "string", required: true },
    ],
    options: [
      { name: "after", kind: "id" },
      { name: "atHeading", kind: "string" },
      { name: "atStart", kind: "string" },
    ],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["insert content at position", "add content after block"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ['node actions.mjs insertBlocks abc123 "New text" --atHeading "Introduction"'],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  setProperties: {
    category: "write",
    summary: "Update page/entry properties (auto-typed)",
    args: [
      { name: "pageId", kind: "id", required: true },
      { name: "props", kind: "json", required: true },
    ],
    options: [],
    aliases: ["updateProperties", "updateProps"],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["update properties", "set status", "change property value"],
    preferInstead: [
      { intent: "update multiple pages", action: "batchSetProperties", reason: "handles N pages in one call" },
    ],
    replacesWorkflows: [],
    examples: [`node actions.mjs setProperties abc123 '{"Status":"Done","Priority":"High"}'`],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: true,
      routeLabel: "Update properties",
      routeCommand: `setProperties <id> '{"Status":"Done"}'`,
      quickPattern: null,
      gotchas: ["Values are auto-typed from the database schema — pass simple values, not raw Notion API format"],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  addComment: {
    category: "write",
    summary: "Add comment to page",
    args: [
      { name: "pageId", kind: "id", required: true },
      { name: "text", kind: "string", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["add a comment", "comment on page"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ['node actions.mjs addComment abc123 "Looks good!"'],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  lockPage: {
    category: "write",
    summary: "Lock page",
    args: [{ name: "pageId", kind: "id", required: true }],
    options: [],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["lock a page"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs lockPage abc123"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  unlockPage: {
    category: "write",
    summary: "Unlock page",
    args: [{ name: "pageId", kind: "id", required: true }],
    options: [],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["unlock a page"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs unlockPage abc123"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  createDatabase: {
    category: "write",
    summary: "Create database with schema",
    args: [
      { name: "parentId", kind: "id", required: true },
      { name: "title", kind: "string", required: true },
      { name: "schema", kind: "json", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["create a database"],
    preferInstead: [
      {
        intent: "create database from markdown table",
        action: "importTable",
        reason: "infers schema from table headers",
      },
    ],
    replacesWorkflows: [],
    examples: [
      `node actions.mjs createDatabase abc123 "Tasks" '{"Status":{"select":{"options":[{"name":"Todo"},{"name":"Done"}]}}}'`,
    ],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  addDatabaseEntry: {
    category: "write",
    summary: "Add row with auto-typed properties",
    args: [
      { name: "dbId", kind: "id", required: true },
      { name: "values", kind: "json", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["add database entry", "add row"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: [`node actions.mjs addDatabaseEntry abc123 '{"Name":"Task 1","Status":"Todo"}'`],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  importTable: {
    category: "write",
    summary: "Create database from markdown table (infers types)",
    args: [
      { name: "parentId", kind: "id", required: true },
      { name: "content", kind: "string", required: true },
    ],
    options: [{ name: "title", kind: "string" }],
    aliases: ["tableToDatabase", "createDatabaseFromTable"],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "low",
    costClass: "moderate",
    compound: false,
    preferredFor: ["convert table to database", "import markdown table"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: [
      'node actions.mjs importTable abc123 "| Name | Status |\\n|---|---|\\n| Task 1 | Done |" --title "Tasks"',
    ],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: true,
      routeLabel: "Markdown table to database",
      routeCommand: 'importTable <parentId> "| md | table |" --title "Name"',
      quickPattern: null,
      gotchas: ["Infers column types from values — numbers, dates, checkboxes, URLs auto-detected"],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  // ── STRUCTURAL ────────────────────────────────────────────────────────
  moveBlocks: {
    category: "structural",
    summary: "Move blocks between pages with rollback",
    args: [
      { name: "sourcePageId", kind: "id", required: true },
      { name: "targetPageId", kind: "id", required: true },
      { name: "blockIds", kind: "array", required: true },
    ],
    options: [{ name: "position", kind: "json" }],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "medium",
    costClass: "moderate",
    compound: false,
    preferredFor: ["move blocks", "transfer blocks between pages"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: [`node actions.mjs moveBlocks srcId targetId '["blockId1","blockId2"]'`],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: {
      workflow: true,
      workflowTitle: "Move Blocks Between Pages",
      workflowNotes: null,
    },
  },

  movePage: {
    category: "structural",
    summary: "Move page (deep copy + archive)",
    args: [
      { name: "pageId", kind: "id", required: true },
      { name: "newParentId", kind: "id", required: true },
    ],
    options: [{ name: "parentType", kind: "string" }],
    aliases: [],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "medium",
    costClass: "expensive",
    compound: false,
    preferredFor: ["move a page", "reparent page"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs movePage abc123 newParentId"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: ["Implemented as deep copy + archive (Notion API has no native move)"],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  reorderBlocks: {
    category: "structural",
    summary: "Reorder blocks by ID array",
    args: [
      { name: "pageId", kind: "id", required: true },
      { name: "newOrder", kind: "array", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "medium",
    costClass: "cheap",
    compound: false,
    preferredFor: ["reorder blocks", "rearrange page content"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: [`node actions.mjs reorderBlocks abc123 '["blockId3","blockId1","blockId2"]'`],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  deepCopy: {
    category: "structural",
    summary: "Full recursive page copy",
    args: [
      { name: "sourcePageId", kind: "id", required: true },
      { name: "targetParentId", kind: "id", required: true },
    ],
    options: [],
    aliases: ["copy", "copyPage", "duplicate"],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "medium",
    costClass: "expensive",
    compound: false,
    preferredFor: ["full copy with subpages", "duplicate page tree"],
    preferInstead: [
      { intent: "copy with modifications", action: "copyPageWith", reason: "reads + modifies + creates in one call" },
    ],
    replacesWorkflows: [],
    examples: ["node actions.mjs deepCopy srcPageId targetParentId"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: true,
      routeLabel: "Full copy with subpages",
      routeCommand: "deepCopy <src> <parent>",
      quickPattern: null,
      gotchas: ["Use copyPageWith instead if you need to modify the copy"],
    },
    docs: {
      workflow: true,
      workflowTitle: "Full Recursive Copy",
      workflowNotes: "Preserves the full page tree structure. Title is copied from the source.",
    },
  },

  copyPageWith: {
    category: "structural",
    summary: "Read + modify + create in one call",
    args: [
      { name: "sourcePageId", kind: "id", required: true },
      { name: "targetParentId", kind: "id", required: true },
      { name: "title", kind: "string", required: true },
    ],
    options: [
      { name: "appendMd", kind: "string" },
      { name: "prependMd", kind: "string" },
      { name: "replaceTitle", kind: "string" },
    ],
    aliases: [],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "low",
    costClass: "moderate",
    compound: true,
    preferredFor: ["copy with modifications", "duplicate and edit", "copy page with changes"],
    preferInstead: [],
    replacesWorkflows: ["getPage + createPage (2 calls)"],
    examples: [
      'node actions.mjs copyPageWith srcId parentId "New Title" --appendMd "## Notes\\nAdded by automation."',
      'node actions.mjs copyPageWith srcId parentId "New Title" --prependMd "## Important\\nThis is a copy."',
    ],
    skill: {
      includeInQuickPatterns: true,
      includeInDecisionTree: true,
      routeLabel: "Copy + modify",
      routeCommand: 'copyPageWith <src> <parent> "Title" --appendMd "## Extra"',
      quickPattern: "Copy with modifications -> `copyPageWith` (1 call)",
      gotchas: [],
    },
    docs: {
      workflow: true,
      workflowTitle: "Copy a Page with Modifications",
      workflowNotes: null,
    },
  },

  mergePages: {
    category: "structural",
    summary: "Combine multiple pages into one",
    args: [
      { name: "sourcePageIds", kind: "array", required: true },
      { name: "targetPageId", kind: "id", required: true },
    ],
    options: [{ name: "archiveSources", kind: "string" }],
    aliases: ["merge"],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "medium",
    costClass: "expensive",
    compound: true,
    preferredFor: ["combine pages", "merge content", "consolidate pages"],
    preferInstead: [],
    replacesWorkflows: ["N x getPage + N x appendBlocks (2N calls)"],
    examples: [`node actions.mjs mergePages '["pageId1","pageId2","pageId3"]' targetId '{"archiveSources": true}'`],
    skill: {
      includeInQuickPatterns: true,
      includeInDecisionTree: true,
      routeLabel: "Merge pages",
      routeCommand: `mergePages '["id1","id2"]' <target>`,
      quickPattern: "Merge pages -> `createPage` -> `mergePages` (2 calls)",
      gotchas: ["Target page must already exist — use createPage first"],
    },
    docs: {
      workflow: true,
      workflowTitle: "Merge Multiple Pages",
      workflowNotes: "Target must already exist — use createPage first.",
    },
  },

  splitPage: {
    category: "structural",
    summary: "Split page at headings into subpages",
    args: [{ name: "pageId", kind: "id", required: true }],
    options: [
      { name: "headingLevel", kind: "number" },
      { name: "createUnderSamePage", kind: "string" },
    ],
    aliases: ["split"],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "medium",
    costClass: "moderate",
    compound: false,
    preferredFor: ["split a page", "break page into subpages"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: [`node actions.mjs splitPage abc123 '{"headingLevel": 2, "createUnderSamePage": true}'`],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: {
      workflow: true,
      workflowTitle: "Split Page into Subpages",
      workflowNotes: null,
    },
  },

  extractSection: {
    category: "read",
    summary: "Get one section's markdown",
    args: [
      { name: "pageId", kind: "id", required: true },
      { name: "headingText", kind: "string", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "markdown", defaultFormat: "markdown", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["read one section", "get section content"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ['node actions.mjs extractSection abc123 "Introduction"'],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: true,
      routeLabel: "Read one section",
      routeCommand: 'extractSection <id> "Heading"',
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  replaceSection: {
    category: "structural",
    summary: "Replace section content (auto-snapshots)",
    args: [
      { name: "pageId", kind: "id", required: true },
      { name: "headingText", kind: "string", required: true },
      { name: "content", kind: "string", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "medium",
    costClass: "cheap",
    compound: false,
    preferredFor: ["edit one section", "replace section content"],
    preferInstead: [],
    replacesWorkflows: ["getPage + find section + delete blocks + insertBlocks (4 calls)"],
    examples: ['node actions.mjs replaceSection abc123 "Overview" "New overview content with **formatting**."'],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: true,
      routeLabel: "Edit one section",
      routeCommand: 'replaceSection <id> "Heading" "new content"',
      quickPattern: null,
      gotchas: [],
    },
    docs: {
      workflow: true,
      workflowTitle: "Replace a Section",
      workflowNotes: "Auto-snapshots before modifying.",
    },
  },

  flattenPage: {
    category: "structural",
    summary: "Inline subpages into parent",
    args: [{ name: "pageId", kind: "id", required: true }],
    options: [],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "high",
    costClass: "moderate",
    compound: false,
    preferredFor: ["flatten page hierarchy", "inline subpages"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs flattenPage abc123"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: ["Destructive — subpages are inlined and archived"],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  nestUnderHeadings: {
    category: "structural",
    summary: "Convert sections to subpages",
    args: [{ name: "pageId", kind: "id", required: true }],
    options: [{ name: "headingLevel", kind: "number" }],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "high",
    costClass: "moderate",
    compound: false,
    preferredFor: ["convert sections to subpages", "nest under headings"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs nestUnderHeadings abc123 --headingLevel 2"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: ["Destructive — content is moved into new subpages"],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  duplicateStructure: {
    category: "structural",
    summary: "Copy hierarchy (empty pages)",
    args: [
      { name: "sourcePageId", kind: "id", required: true },
      { name: "targetParentId", kind: "id", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "low",
    costClass: "moderate",
    compound: false,
    preferredFor: ["copy page structure", "duplicate hierarchy without content"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs duplicateStructure srcId targetParentId"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  applyTemplate: {
    category: "structural",
    summary: "Template with {{placeholders}}",
    args: [
      { name: "templatePageId", kind: "id", required: true },
      { name: "targetParentId", kind: "id", required: true },
      { name: "variables", kind: "json", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "low",
    costClass: "moderate",
    compound: true,
    preferredFor: ["apply a template", "create from template"],
    preferInstead: [],
    replacesWorkflows: ["deepCopy + manual find-replace"],
    examples: [`node actions.mjs applyTemplate templateId parentId '{"name":"Acme Corp","date":"2026-03-05"}'`],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: {
      workflow: true,
      workflowTitle: "Template with Variable Substitution",
      workflowNotes: null,
    },
  },

  // ── BATCH ─────────────────────────────────────────────────────────────
  batchSetProperties: {
    category: "batch",
    summary: "Update properties on multiple pages",
    args: [
      { name: "pageIds", kind: "array", required: true },
      { name: "props", kind: "json", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "medium",
    costClass: "moderate",
    compound: true,
    preferredFor: ["bulk property update", "update multiple pages", "batch update"],
    preferInstead: [],
    replacesWorkflows: ["N x setProperties (N calls)"],
    examples: [`node actions.mjs batchSetProperties '["id1","id2","id3"]' '{"Status":"Done"}'`],
    skill: {
      includeInQuickPatterns: true,
      includeInDecisionTree: true,
      routeLabel: "Batch update",
      routeCommand: `batchSetProperties '["id1","id2"]' '{"Status":"Done"}'`,
      quickPattern: "Batch property update -> `batchSetProperties` (1 call)",
      gotchas: [],
    },
    docs: {
      workflow: true,
      workflowTitle: "Batch Update Properties",
      workflowNotes: null,
    },
  },

  batchArchive: {
    category: "batch",
    summary: "Archive multiple pages",
    args: [{ name: "pageIds", kind: "array", required: true }],
    options: [],
    aliases: ["archive"],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "high",
    costClass: "moderate",
    compound: true,
    preferredFor: ["archive multiple pages", "bulk archive"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: [`node actions.mjs batchArchive '["id1","id2","id3"]'`],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: ["Archived pages are soft-deleted (recoverable in Notion UI)"],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  batchTag: {
    category: "batch",
    summary: "Tag pages with select value",
    args: [
      { name: "pageIds", kind: "array", required: true },
      { name: "property", kind: "string", required: true },
      { name: "value", kind: "string", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "medium",
    costClass: "moderate",
    compound: true,
    preferredFor: ["tag multiple pages", "bulk tag"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: [`node actions.mjs batchTag '["id1","id2"]' "Category" "Engineering"`],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  // ── SAFETY ────────────────────────────────────────────────────────────
  snapshot: {
    category: "safety",
    summary: "In-memory snapshot (max 20)",
    args: [{ name: "pageId", kind: "id", required: true }],
    options: [],
    aliases: [],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["snapshot before editing", "save page state"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs snapshot abc123"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: ["Max 20 snapshots per session — oldest are evicted"],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  restore: {
    category: "safety",
    summary: "Restore from snapshot",
    args: [{ name: "snapId", kind: "string", required: true }],
    options: [],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "medium",
    costClass: "moderate",
    compound: false,
    preferredFor: ["restore snapshot", "undo changes"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs restore snap_abc123"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  backupPage: {
    category: "safety",
    summary: "Recursive backup to disk",
    args: [
      { name: "pageId", kind: "id", required: true },
      { name: "dirPath", kind: "path", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "moderate",
    compound: false,
    preferredFor: ["backup a page", "save page to disk"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs backupPage abc123 /tmp/backup"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  backupDatabase: {
    category: "safety",
    summary: "Export schema + entries to disk",
    args: [
      { name: "dbId", kind: "id", required: true },
      { name: "dirPath", kind: "path", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "status", defaultFormat: "json", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "moderate",
    compound: false,
    preferredFor: ["backup a database"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs backupDatabase abc123 /tmp/backup"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  transact: {
    category: "safety",
    summary: "Multi-op with rollback",
    args: [{ name: "operations", kind: "json", required: true }],
    options: [],
    aliases: [],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: true,
    risk: "medium",
    costClass: "moderate",
    compound: true,
    preferredFor: ["atomic multi-step operation", "transactional update"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: [
      `node actions.mjs transact '[{"action":"setProperties","pageId":"id1","props":{"Status":"Done"}},{"action":"appendBlocks","pageId":"id2","content":"Updated"}]'`,
    ],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: ["Rollback is best-effort — some operations may not be fully reversible"],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  // ── ANALYSIS ──────────────────────────────────────────────────────────
  workspaceMap: {
    category: "analysis",
    summary: "All pages and databases",
    args: [],
    options: [],
    aliases: [],
    output: { kind: "json", defaultFormat: "text", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "expensive",
    compound: false,
    preferredFor: ["workspace overview", "list all pages", "show workspace"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs workspaceMap"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: true,
      routeLabel: "Find something",
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  pageStats: {
    category: "analysis",
    summary: "Block count, depth, word count",
    args: [{ name: "pageId", kind: "id", required: true }],
    options: [],
    aliases: [],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "cheap",
    compound: false,
    preferredFor: ["page statistics", "page metrics"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs pageStats abc123"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  diffPages: {
    category: "analysis",
    summary: "Line-level page comparison",
    args: [
      { name: "pageId1", kind: "id", required: true },
      { name: "pageId2", kind: "id", required: true },
    ],
    options: [],
    aliases: [],
    output: { kind: "string", defaultFormat: "text", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "moderate",
    compound: false,
    preferredFor: ["compare pages", "diff pages"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs diffPages pageId1 pageId2"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  findDuplicates: {
    category: "analysis",
    summary: "Pages with same title",
    args: [],
    options: [],
    aliases: [],
    output: { kind: "list", defaultFormat: "text", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "expensive",
    compound: false,
    preferredFor: ["find duplicate pages", "detect duplicates"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs findDuplicates"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  findOrphans: {
    category: "analysis",
    summary: "Root-level pages",
    args: [],
    options: [],
    aliases: [],
    output: { kind: "list", defaultFormat: "text", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "expensive",
    compound: false,
    preferredFor: ["find orphan pages", "find root pages"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs findOrphans"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  findEmpty: {
    category: "analysis",
    summary: "Pages with no content",
    args: [],
    options: [],
    aliases: [],
    output: { kind: "list", defaultFormat: "text", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "expensive",
    compound: false,
    preferredFor: ["find empty pages"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs findEmpty"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  findStale: {
    category: "analysis",
    summary: "Pages not edited in N days",
    args: [{ name: "days", kind: "number", required: false }],
    options: [],
    aliases: [],
    output: { kind: "list", defaultFormat: "text", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "expensive",
    compound: false,
    preferredFor: ["find stale pages", "check for outdated pages"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs findStale 30"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },

  suggestReorganization: {
    category: "analysis",
    summary: "Structure improvement suggestions",
    args: [{ name: "pageId", kind: "id", required: true }],
    options: [],
    aliases: [],
    output: { kind: "json", defaultFormat: "json", supportsRaw: false },
    mutates: false,
    risk: "low",
    costClass: "moderate",
    compound: false,
    preferredFor: ["suggest reorganization", "improve page structure"],
    preferInstead: [],
    replacesWorkflows: [],
    examples: ["node actions.mjs suggestReorganization abc123"],
    skill: {
      includeInQuickPatterns: false,
      includeInDecisionTree: false,
      routeLabel: null,
      routeCommand: null,
      quickPattern: null,
      gotchas: [],
    },
    docs: { workflow: false, workflowTitle: null, workflowNotes: null },
  },
};

// ── Derived exports (backward-compatible) ─────────────────────────────

/** ACTIONS — same { args: string[], options: string[] } shape as before */
export const ACTIONS = Object.fromEntries(
  Object.entries(ACTION_CATALOG).map(([k, v]) => [
    k,
    { args: v.args.map((a) => a.name), options: v.options.map((o) => o.name) },
  ]),
);

/** Convert snake_case to camelCase */
export function toCamelCase(str) {
  return str.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

/** Common action aliases — derived from ACTION_CATALOG */
export const ACTION_ALIASES = Object.fromEntries(
  Object.entries(ACTION_CATALOG).flatMap(([action, meta]) => (meta.aliases || []).map((alias) => [alias, action])),
);

/** Resolve action name with alias fallback */
export function resolveAction(name) {
  const camel = toCamelCase(name);
  return ACTION_ALIASES[camel] || camel;
}

/** Get the full catalog */
export function getActionCatalog() {
  return ACTION_CATALOG;
}

/** Get full metadata for one action (with alias resolution) */
export function getActionMeta(name) {
  const resolved = resolveAction(name);
  return ACTION_CATALOG[resolved] ? { name: resolved, ...ACTION_CATALOG[resolved] } : null;
}
